Register page
aoomsAP/the-one-quiz pull request #3
Opened 2023-10-08 15:35 UTC by Chiani-Egels

Created a register page using (tried) semantic HTML as requested.

2023-10-08 17:01 UTC, aoomsAP requested changes

2023-10-08 17:01 UTC, aoomsAP commented on views/register.ejs
> +<div class="container mt-5 row justify-content-center">
Er klopt hier wel iets niet want uw registreer element staat niet effectief gecentreerd op desktop. Wordt max-width 1320px of zoiets gehanteerd. Is dat misschien door het gebruik van die row/col dingen als class, dat je een form als grid hebt willen doen? Dat is niet per se nodig hier omdat alles gecentreerd is. Ik zou via #id in css dan een max-width toevoegen misschien. Maar momenteel heb je die css file nog niet gepulled, dus ofwel moet je dat in een nieuwe branch aanpassen (bv #register, #login max width = 500px of whatever), ofwel moeten we dat fixen wanneer we alle margins/paddings gaan corrigeren.

2023-10-11 17:39 UTC, Chiani-Egels commented
Changed code as requested. Please have a look now.

2023-10-11 22:29 UTC, aoomsAP approved these changes

2023-10-11 22:29 UTC, merged