Score functionality created, some unresolved errors
aoomsAP/the-one-quiz pull request #56
Opened 2023-11-16 21:00 UTC by Chiani-Egels

There's an error on the highScore variable. I've tried resolving it, but got nowhere. I could also use some feedback on the code in general, if it's correct or what is unnecessary.

2023-11-17 02:26 UTC, aoomsAP requested changes

2023-11-17 02:26 UTC, aoomsAP commented on index.ts
> +
This was really well done honestly, all the review comments I made were rather minor. Score functionality works perfectly as far as I can tell, and writing new high score to database also works.

2023-11-17 02:26 UTC, aoomsAP commented on index.ts
> +                let consecutiveCorrect = 0;
"**consecutiveCorrect**" variable doesn't seem to be used anywhere, so I'd delete it. You calculate the score into the "scores" array anyway, and afterwards in sumOfScores. So "consecutiveCorrect" is not needed.
(On line 309 as well)

2023-11-19 13:24 UTC, Chiani-Egels commented
I've made the requested changes and added the div to show the right answers for the questions. Further styling will be done in the next sprint.

2023-11-19 14:22 UTC, aoomsAP approved these changes

2023-11-19 14:25 UTC, merged